"""add job title to employee

Revision ID: 7f76f34e3f66
Revises: 2226883368c9
Create Date: 2026-05-01 18:05:21.205868

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f76f34e3f66"
down_revision: str | None = "2226883368c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("job_title", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "job_title")
    # ### end Alembic commands ###
