profile: devcontainer

app:
  environment: devcontainer
  logging: logging.yaml

  database:
    username: postgres
    password: postgres
    host: db
    port: 5432
    echo: False
    name: alloq-db
